# Generated by Django 6.0 on 2025-12-05 20:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
