# Generated by Django 6.0 on 2025-12-10 23:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_workerprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CLIENT', 'Client'), ('WORKER', 'Worker'), ('COMPANY', 'Company')], default='CLIENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='profession',
            field=models.CharField(choices=[('PLUMBER', 'Plumber'), ('ELECTRICIAN', 'Electrician'), ('MASON', 'Mason'), ('PAINTER', 'Painter'), ('CARPENTER', 'Carpenter'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Years of Experience'),
        ),
    ]
