# Generated by Django 6.0 on 2026-01-27 23:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(verbose_name='Query Original')),
                ('processed_query', models.TextField(verbose_name='Query Procesada')),
                ('strategy_used', models.CharField(choices=[('tfidf', 'TF-IDF Puro'), ('fallback', 'Geo + Rating'), ('hybrid', 'Híbrido (TF-IDF + Rating + Geo)')], max_length=20, verbose_name='Estrategia Usada')),
                ('filters_applied', models.JSONField(blank=True, default=dict, verbose_name='Filtros Aplicados')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Resultados')),
                ('top_worker_ids', models.JSONField(default=list, help_text='Lista de IDs de trabajadores recomendados en orden', verbose_name='IDs de Top Trabajadores')),
                ('response_time_ms', models.FloatField(default=0.0, verbose_name='Tiempo de Respuesta (ms)')),
                ('cache_hit', models.BooleanField(default=False, verbose_name='Hit en Cache')),
                ('click_position', models.PositiveIntegerField(blank=True, help_text='Posición (0-indexed) del trabajador clickeado en los resultados', null=True, verbose_name='Posición del Click')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user_latitude', models.FloatField(blank=True, null=True, verbose_name='Latitud del Usuario')),
                ('user_longitude', models.FloatField(blank=True, null=True, verbose_name='Longitud del Usuario')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_queries', to=settings.AUTH_USER_MODEL)),
                ('worker_clicked', models.ForeignKey(blank=True, help_text='Trabajador que el usuario clickeó (si alguno)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicked_from_recommendations', to='users.workerprofile')),
                ('worker_hired', models.ForeignKey(blank=True, help_text='Trabajador que fue contratado (conversión)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_from_recommendations', to='users.workerprofile')),
            ],
            options={
                'verbose_name': 'Log de Recomendación',
                'verbose_name_plural': 'Logs de Recomendaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='users_recom_created_2a6244_idx'), models.Index(fields=['strategy_used', '-created_at'], name='users_recom_strateg_25deb8_idx'), models.Index(fields=['user', '-created_at'], name='users_recom_user_id_d6e877_idx')],
            },
        ),
    ]
