# Generated by Django 6.0 on 2026-02-10 19:09

import django.core.validators
import django.db.models.deletion
import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_recommendationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Título breve describiendo el trabajo (ej: 'Remodelación de Cocina')", max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del proyecto y técnicas utilizadas', verbose_name='Descripción')),
                ('image', models.ImageField(help_text='Foto antes/después o muestra del proyecto (máx 2MB)', upload_to=users.models.portfolio_image_upload_to, validators=[users.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), users.validators.ImageContentTypeValidator()], verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('worker', models.ForeignKey(help_text='Trabajador dueño de este item de portfolio', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='users.workerprofile', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Item de Portfolio',
                'verbose_name_plural': 'Items de Portfolio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['worker', '-created_at'], name='portfolio_worker_created_idx')],
            },
        ),
    ]
