# Generated by Django 6.0 on 2026-02-17 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_review'),
        ('users', '0006_add_portfolio_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='is_external_work',
            field=models.BooleanField(default=True, help_text='Indica si es un trabajo fuera de la plataforma', verbose_name='Trabajo Externo'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Orden de servicio completada asociada a este proyecto (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='orders.serviceorder', verbose_name='Orden Relacionada'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['order'], name='portfolio_order_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_external_work'], name='portfolio_external_idx'),
        ),
    ]
