# Generated by Django 6.0 on 2026-05-25 21:43

import django.core.validators
import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(help_text='Foto antes/después o muestra del proyecto (máx 5MB)', upload_to=users.models.portfolio_image_upload_to, validators=[users.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), users.validators.ImageContentTypeValidator()], verbose_name='Imagen'),
        ),
    ]
