# Generated by Django 6.0 on 2026-01-09 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHoursLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Work Date')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Ejemplo: 5.5 para 5 horas y 30 minutos', max_digits=5, verbose_name='Hours Worked')),
                ('description', models.TextField(blank=True, help_text='Descripción de las tareas realizadas', verbose_name='Work Description')),
                ('approved_by_client', models.BooleanField(default=False, verbose_name='Approved by Client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Work Hours Log',
                'verbose_name_plural': 'Work Hours Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='serviceorder',
            name='order_metrics_idx',
        ),
        migrations.AddField(
            model_name='workhourslog',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='orders.serviceorder', verbose_name='Service Order'),
        ),
        migrations.AlterUniqueTogether(
            name='workhourslog',
            unique_together={('service_order', 'date')},
        ),
    ]
