# Generated by Django 6.0 on 2026-01-14 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_workhourslog_remove_serviceorder_order_metrics_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido del mensaje de texto', verbose_name='Message Content')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.serviceorder', verbose_name='Service Order')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['service_order', 'timestamp'], name='orders_mess_service_6d51f3_idx'), models.Index(fields=['sender', 'timestamp'], name='orders_mess_sender__9612a4_idx')],
            },
        ),
    ]
