# Generated by Django 6.0 on 2026-01-19 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_message'),
        ('users', '0004_alter_user_first_name_alter_user_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['client', 'status'], name='order_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['worker', 'status'], name='order_worker_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status', 'created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workhourslog',
            index=models.Index(fields=['service_order', 'approved_by_client'], name='workhours_order_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='workhourslog',
            index=models.Index(fields=['date'], name='workhours_date_idx'),
        ),
    ]
