# Generated by Django 6.0 on 2026-01-21 22:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_serviceorder_order_client_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(help_text='Mínimo 10 caracteres', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('service_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.serviceorder', verbose_name='Service Order')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_order'], name='review_order_idx'), models.Index(fields=['-created_at'], name='review_created_idx')],
            },
        ),
    ]
